spring.application.name=helpdesk


# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/helpdesk
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update